# Generated by Django 5.0.7 on 2024-07-26 13:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0017_rename_id_vehicle_v_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='v_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
