# Generated by Django 5.0.7 on 2024-07-26 13:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0019_vehicle_id_alter_vehicle_v_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='v_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
