# Generated by Django 5.0.7 on 2024-07-26 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0020_alter_vehicle_v_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='v_id',
        ),
    ]
